// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: hashring.proto

package dcache

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HashRingNode_Set_FullMethodName = "/dcache.HashRingNode/Set"
	HashRingNode_Get_FullMethodName = "/dcache.HashRingNode/Get"
)

// HashRingNodeClient is the client API for HashRingNode service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HashRingNodeClient interface {
	Set(ctx context.Context, in *KeyValue, opts ...grpc.CallOption) (*SetResponse, error)
	Get(ctx context.Context, in *KeyRequest, opts ...grpc.CallOption) (*GetResponse, error)
}

type hashRingNodeClient struct {
	cc grpc.ClientConnInterface
}

func NewHashRingNodeClient(cc grpc.ClientConnInterface) HashRingNodeClient {
	return &hashRingNodeClient{cc}
}

func (c *hashRingNodeClient) Set(ctx context.Context, in *KeyValue, opts ...grpc.CallOption) (*SetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetResponse)
	err := c.cc.Invoke(ctx, HashRingNode_Set_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hashRingNodeClient) Get(ctx context.Context, in *KeyRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, HashRingNode_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HashRingNodeServer is the server API for HashRingNode service.
// All implementations must embed UnimplementedHashRingNodeServer
// for forward compatibility.
type HashRingNodeServer interface {
	Set(context.Context, *KeyValue) (*SetResponse, error)
	Get(context.Context, *KeyRequest) (*GetResponse, error)
	mustEmbedUnimplementedHashRingNodeServer()
}

// UnimplementedHashRingNodeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHashRingNodeServer struct{}

func (UnimplementedHashRingNodeServer) Set(context.Context, *KeyValue) (*SetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Set not implemented")
}
func (UnimplementedHashRingNodeServer) Get(context.Context, *KeyRequest) (*GetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedHashRingNodeServer) mustEmbedUnimplementedHashRingNodeServer() {}
func (UnimplementedHashRingNodeServer) testEmbeddedByValue()                      {}

// UnsafeHashRingNodeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HashRingNodeServer will
// result in compilation errors.
type UnsafeHashRingNodeServer interface {
	mustEmbedUnimplementedHashRingNodeServer()
}

func RegisterHashRingNodeServer(s grpc.ServiceRegistrar, srv HashRingNodeServer) {
	// If the following call pancis, it indicates UnimplementedHashRingNodeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HashRingNode_ServiceDesc, srv)
}

func _HashRingNode_Set_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KeyValue)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HashRingNodeServer).Set(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HashRingNode_Set_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HashRingNodeServer).Set(ctx, req.(*KeyValue))
	}
	return interceptor(ctx, in, info, handler)
}

func _HashRingNode_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HashRingNodeServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HashRingNode_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HashRingNodeServer).Get(ctx, req.(*KeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HashRingNode_ServiceDesc is the grpc.ServiceDesc for HashRingNode service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HashRingNode_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dcache.HashRingNode",
	HandlerType: (*HashRingNodeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Set",
			Handler:    _HashRingNode_Set_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _HashRingNode_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hashring.proto",
}
